IBM/ibm-crossplane

Makefile, README.md, common/Makefile.common.mk
Fixes #
Add support of ppc64le and s390x
I have:
=> add multi-arch support

OWNERS.md, SECURITY_CONTACTS
Fixes #
add OWNERS and SECURITY_CONTACTS
I have:
=> add OWNERS and SECURITY_CONTACTS

internal/controller/apiextensions/composite/reconciler.go
Fixes #
Modify Crossplane to render resources in composition synchronously after each easy resource is `ready`
I have:
=> render composition resources in sequential order

ibm/Makefile.common.mk
Fixes #
Fixed `make images` in prow build, where we need to rebuild all images when running in a new container
I have:
=> Crossplane 1.0: fix broken images make target

ibm/Makefile.common.mk
Fixes #
`make images` not pushing images to integration due to `config-docker` target didn't get executed
I have:
=> Crossplane 1.0: fix images not pushed to integration

internal/controller/apiextensions/composite/api.go, internal/controller/apiextensions/composite/composed.go, internal/controller/apiextensions/composite/reconciler.go
Fixes #
1. IBM modification to composition to render resources in sequential order
2. Default the connection secrets namespace to the namespace where Crossplane is deployed
I have:
=> Crossplane 1.0: IBM modifications to Crossplane

internal/controller/apiextensions/composite/api.go
Fixes #
Add support to define a common default label to select composition. To define the default value, add these env variables to the crossplane deployment
- DEFAULT_LABEL_NAME
- DEFAULT_LABEL_VALUE
I have:
=> add default label support

internal/controller/apiextensions/composite/api.go, internal/controller/apiextensions/composite/api_test.go
=> add provider reading from Configuration labels

ibm/Makefile.common.mk
=> skip pushing images

Makefile
Override targets from build submodule installing helm.
I have:
=> Override targets installing helm

internal/controller/apiextensions/composite/composed.go
=> fix for kafkaUser

internal/controller/apiextensions/composite/composed.go
=> fix for kafkaUser`

internal/controller/apiextensions/composite/reconciler.go
Fixes #
Problems with informers and permissions for Secrets
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/49767
I have:
=> add new client also for ConnectionDetailsFetcher

internal/controller/pkg/manager/reconciler.go, internal/controller/pkg/manager/reconciler_test.go
Change 'fromEnvVar' to 'FromEnvVar'
Fixes  [#49622](https://github.ibm.com/ibmprivatecloud/roadmap/issues/49622)
I have:
=> Fix typo in 'FromEnvVar'

internal/controller/pkg/manager/reconciler.go, internal/controller/pkg/manager/reconciler_test.go
=> revert config name

internal/controller/apiextensions/composite/api.go
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/49244
I have:
=> External Kafka Support

internal/xpkg/fetch.go
=> fix for SA for zen

internal/xpkg/fetch.go
Fixes # https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50526
I have:
=> Fix sa zen

.github/workflows/ci.yml
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51462
I have:
=> remove codecov from github action

Makefile, ibm/Makefile.common.mk
Fixes https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51506
I have:
=> Change golang version constraints

go.mod, go.sum
=> update docker cli

.github/workflows/ci.yml
=> update go to 1.17.8

cmd/crank/build.go, internal/xpkg/cache.go, internal/xpkg/name.go, internal/xpkg/name_test.go
To prevent possible path traversal attack
Fixes #
I have:
=> sanitize buidPath function

.github/workflows/ci.yml
=> update go version

.github/workflows/ci.yml
=> bump go version

.github/workflows/ci.yml
=> update golang version

cluster/charts/crossplane/values.yaml.tmpl, ibm/Makefile.common.mk, ibm/scripts/config_docker.sh
=> Updated registry endpoint

ibm/scripts/config_docker.sh
=> Change artifactory url in login method

go.mod, go.sum
=> Update client_golang dependency

.github/workflows/ci.yml, .golangci.yml, Makefile, apis/generate.go, internal/client/clientset/versioned/fake/register.go, internal/client/clientset/versioned/scheme/register.go, internal/controller/apiextensions/composite/api_test.go, internal/feature/generate.go, test/e2e/apiextensions/composition_test.go, test/e2e/pkg/dependency_test.go
=> Update golang ci lint and go version

.github/workflows/ci.yml
=> Update go to 1.20.3

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/commands.yml, .github/workflows/tag.yml
=> Update ubuntu runner to 20.04

OWNERS, go.mod, go.sum
=> Update docker version to latest

.github/workflows/ci.yml
=> Bump golang version

go.mod
=> Update docker distro in required

.github/workflows/ci.yml
=> Update go to 1.20.5

go.mod, go.sum
=> upgrade logrus package to v1.9.3

go.mod, go.sum
=> Upgrade docker to v24.0.7
